spring.datasource.url=jdbc:mysql://localhost:3306/incidencias_db?useSSL=false&serverTimezone=America/Mexico_City&allowPublicKeyRetrieval=true
spring.datasource.username=incidencias_user
spring.datasource.password=incidencias_pass
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

telegram.bot.token=8785497033:AAG8UYRT_MxHItOwdtasCDOKKNp7hKxq6E8
telegram.chat.id=-5339947823
notifications.telegram.enabled=true