spring.application.name=gestion-incidencias-operativas

server.port=8081

spring.profiles.active=local

#graph.tenant-id=${GRAPH_TENANT_ID}
#graph.client-id=${GRAPH_CLIENT_ID}
#graph.client-secret=${GRAPH_CLIENT_SECRET}
graph.tenant-id=TU_TENANT_ID
graph.client-id=TU_CLIENT_ID
graph.client-secret=TU_CLIENT_SECRET
graph.scope=https://graph.microsoft.com/.default
graph.token-url=https://login.microsoftonline.com/${graph.tenant-id}/oauth2/v2.0/token

#################################################
# Mail Provider
#################################################

mail.provider=pst

pst.file-path=E:/Correo (No Borrar)/Correo2025.pst
pst.folder-name=Operacion e Incidencias
pst.max-mails=10
pst.only-unprocessed=true




